version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_TRIPCOM_API_KEY=${VITE_TRIPCOM_API_KEY}
      - VITE_TRIPCOM_API_URL=${VITE_TRIPCOM_API_URL}
